### ISSUE TITLE
error activate

### ISSUE THREAD

**Issue by piticu81** [Katamaze/WHMCS-Watchdog#1]
Unable to create mod_addonexample: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'wd_audit' already exists (SQL: create table `wd_audit` (`path` varchar(260) not null, `detected` char(32) not null, `expected` char(32) null, `status` tinyint not null) default character set utf8 collate 'utf8_unicode_ci')

**Comment by Kian987** [comment]
Quoting from read me

> Please keep in mind that the module is not ready for use as we're still working on it. It won't take much time since we're "converting" a stand-alone script to make it work as a WHMCS Addon module.
